### This is a PyCharm http request file

### Create Archive
POST http://localhost:5001/api/archive/create
Accept: application/json

{ "urls": ["http://www.google.com", "http://www.yahoo.com", "https://www.godaddy.com"] }

### Get Status
GET http://localhost:5001/api/archive/status/183caed6-c6ac-4420-9e0e-bf5b0be819ce

### Get a file
GET http://localhost:5001/api/archive/get/183caed6-c6ac-4420-9e0e-bf5b0be819ce