### Create Archive
POST http://127.0.0.1:5000/api/archive/create
Accept: application/json

{ "urls": ["1", "2"] }

### Get Status
GET http://127.0.0.1:5000/api/archive/status/973be497-f935-4066-a512-957f5e761113